services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "127.0.0.1:3030:3030"
    volumes:
      - ./frontend/src:/app/src
    networks:
      - app-network


  backend:
    build:
      context: ./backend
    ports:
      - "127.0.0.1:5030:5030"
    volumes:
      - ./backend/src:/app/src
    networks:
      - app-network

  ollama:
    build:
      context: ./ollama
    volumes:
      - ./ollama/src:/app/src
    ports:
      - "127.0.0.1:11434:11434"
      - "127.0.0.1:11435:11435"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - backend
      - ollama
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/htpasswd/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/blocklist.conf:/etc/nginx/blocklist.conf:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
